# Generated by Django 5.0.6 on 2024-07-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prendas', '0004_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='prendasropa',
            name='foto',
            field=models.ImageField(default='prendas/default.jpg', upload_to='prendas/'),
        ),
    ]
